[package]
name = "dendrite-lsp"
version.workspace = true
edition = "2021"

[dependencies]
dendrite-core = { path = "../dendrite-core" }
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
url = "2.5"
serde = { version = "1.0", features = ["derive"] }